import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BottomNav from "@/components/BottomNav";
import { AppContextProvider } from "@/context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full min-h-screen flex flex-col">
        <AppContextProvider>
          <Navbar />

          <main className="flex-1 min-h-0 pb-24 md:pb-20 overflow-auto">
            {children}
          </main>

          <div className="md:hidden">
            <BottomNav />
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
